from enum import Enum

class Location(Enum):
    SHN_CENTENARY_HOSPITAL = "CHV"
    CENTENNIAL_COLLEGE = "CCV"
    CAREFIRST_SENIORS = "CSV"
    SCARBOROUGH_CENTRE = "BEV"
    TAIBU_COMMUNITY_HEALTH_CENTRE = "TCV"
