from enum import Enum

class PriorityArea(Enum):
    ELIGIBLE_AGE_GROUPS = "OLDER"
    ADULT_RECIPIENTS_OF_CHRONIC_HOME_CAREFIRST = "OLDER"
    INDIGENOUS_ADULT = "OLDER"
    PRIORITY_HEALTHCARE_WORKERS = "OLDER"
    FAITH_LEADERS = "OLDER"
    PEOPLE_WITH_HEALTH_CONDITIONS = "OLDER"
    EDUCATION_WORKERS = "OLDER"
    TRANSPLANT_AND_CHEMOTHERAPY_RECIPIENTS = "CHEMO"